name: 05-1-filters-activity-types

on: 
    pull_request:
        types:
            - opened
            - synchronize
        branches:
            - main

jobs:
    echo: 
        runs-on: ubuntu-latest
        steps:
            - run: echo "Runniing whenever a PR is opened or synched and base branch is main"

