name: 06 - Contexts
run-name: 06 - contexts | DEBUG  - ${{ inputs.debug }}

on:
    push:
    workflow_dispatch:
        inputs:
          debug:
            description: describes the debug message
            type: boolean
            default: false

jobs: 
    echo-data:
        runs-on: ubuntu-latest
        steps:
          - name: Display information
            run: |
                echo "Event Name: ${{ github.event_name }}"
                echo "Ref: ${{ github.ref }}"
                echo "SHA: ${{ github.sha }}"
                echo "Actor: ${{ github.Actor }}"
                echo "Workflow: ${{ github.workflow }}"
                echo "Run ID: ${{ github.run_id }}"
                echo "Run Number: ${{ github.run_number }}"
          - name: Retrieve Variable
            run: |
                echo "Variable value: ${{ vars.MY_VAR }}"
                # echo "Ref: ${{ github.ref }}"
                # echo "Ref: ${{ github.ref }}"
                # echo "Ref: ${{ github.ref }}"